### ISSUE TITLE
Runtime Configurability

### ISSUE THREAD

**Issue by Aklakan** [AKSW/RDFauthor#12]
RDFauthor should be configurable during runtime, which means, that for each option that is set using RDFa or Link-Elements, there should be corresponding methods on the RDFauthor object: Specifically I would need the following methods:

.setSourceService("http://dbpedia.org/sparql");
.setSourceGraphs([/_array of graph URIs_/]);
.setTargetService("http://localhost/sparql");
.setTargetGraph("http://write.me");

.setData(/\* good question what to accept here */);

Ideally, .setData should probably accept some normalized representation of RDF data (maybe some standard interfaces; no idea if this is useful: https://github.com/webr3/rdf-interfaces) . For me it would be sufficient if there was a Talis RdfJson interface.

Please also name the methods with source-target rather than following the current namings with query-update.

**Comment by seebi** [comment]
why do you need the setData?

**Comment by cannelony** [comment]
future use case as discussed:
var rdfAauthor = new RdfAuthor({
targetService: "http://localhost/sparql",
targetGraph: "http://mygraph.org/",
targetResource="http://myresource-which-i-want-to-edit",
targetResourceData: /\* talisJson mit den resourcen daten --- wenn nicht gesetzt, macht RDFauthor selbst ein query, um alle tripel für die resource abzuholen */
});
