### ISSUE TITLE
GeoWidget conflicts with existing OpenLayers map.

### ISSUE THREAD

**Issue by Aklakan** [AKSW/RDFauthor#29]
Closing RDFauthor completely messes up the behaviour of my existing OpenLayers map.
It also yields the following error in the console:
Uncaught TypeError: Cannot call method 'stop' of undefined 
Uncaught TypeError: Object #<Object> has no method 'getViewportElement' 

I see that the GeoWidget adds a hidden div to the document body.

Not yet sure which OpenLayers instance (main map view or geowidget) is causing these errors.
We will have to look closer at this issue at some point.

**Comment by seebi** [comment]
hi @cannelony - maybe you can look into this soon?

**Comment by seebi** [comment]
hi @Aklakan - do you still need this fix?

**Comment by seebi** [comment]
time out :-)
