### ISSUE TITLE
add date widget property hook

### ISSUE THREAD

**Issue by seebi** [AKSW/RDFauthor#34]
Please add a property hook to the dateTime widget to edit values of the following properties with the widget:

http://purl.org/dc/elements/1.1/issued
http://purl.org/dc/elements/1.1/modified
http://purl.org/dc/terms/created
http://purl.org/dc/terms/modified
http://vocab.ox.ac.uk/projectfunding#startDate
http://vocab.ox.ac.uk/projectfunding#endDate
http://schema.org/availabilityEnds
http://schema.org/availabilityStarts
http://schema.org/birthDate
http://schema.org/commentTime
http://schema.org/dateCreated
http://schema.org/dateModified
http://schema.org/datePosted
http://schema.org/datePublished
http://schema.org/deathDate
http://schema.org/endDate
http://schema.org/expires
http://schema.org/foundingDate
http://schema.org/guidelineDate
http://schema.org/lastReviewed
http://schema.org/ownedFrom
http://schema.org/ownedThrough
http://schema.org/priceValidUntil
http://schema.org/releaseDate
http://schema.org/startDate
http://schema.org/uploadDate
http://schema.org/validFrom
http://schema.org/validThrough

**Comment by cannelony** [comment]
i added the properties. the datetimepicker will executed. Or should the datepicker be executed?

**Comment by seebi** [comment]
please use the date widget
