### ISSUE TITLE
Error when editing properties

### ISSUE THREAD

**Issue by white-gecko** [AKSW/RDFauthor#37]
When I click on "Edit Properties" and than change a properties content and click "Save Changes" I get the following error and nothing else happens:

```
TypeError: json[r][p][o].value is undefined
http://…/OntoWiki/libraries/RDFauthor/src/rdfauthor.js
Line 1017
```

If I click the "Save Changes" button again RDFauthor reloads the page but doesn't store the changes.

**Comment by white-gecko** [comment]
"Add Properties" without clicking "Edit Properties" before works.

**Comment by white-gecko** [comment]
It happens only under some strange conditions, I can reproduce this behavior with two instances in one knowledge base but I can't reproduce it by creating similar instances. I hope it will not happen again.

**Comment by seebi** [comment]
you can still reproduce that?

**Comment by white-gecko** [comment]
Yes and it occurres on Chromium and Firefox. So I don't know if it is related to AKSW/OntoWiki#186

**Comment by cannelony** [comment]
I can not reproduce the issue.

**Comment by white-gecko** [comment]
I can only reproduce it in one special model. I have to find out, what the special property of the model is which causes the issue.
