### ISSUE TITLE
Property edition works with 'Edit Resource' but not with 'Edit properties' for instance in namespace 

### ISSUE THREAD

**Issue by white-gecko** [AKSW/RDFauthor#47]
From https://github.com/AKSW/OntoWiki/issues/333 (@cfrancois7):

Dear all,

I'm face with several issues regarding the edition of resources on ontowiki.
I'm using the AKSW templates
1. I use the "Admin" account
2. I uploaded a RDF with all relations into the namespace.
3. I **can't edit the resource properties** through the property edition menu and with "Edit Properties" **if this property is inside the namespace**.[Image](https://www.dropbox.com/s/9rea791hgn3nsz4/edition_resources_not_possible.png?dl=0)
4. But I can edit the resource properties through the `right click` on the resource instance and `edit resources`.[ Image](https://www.dropbox.com/s/r75kzxstkch8vu8/edition_resources.png?dl=0)
   That's the first problem

The second problem is when I add property
0. I use the "Admin" account
1. same as above
2. The add of new property with the `Add property` works. I can create it but after I **can't edit *_as seen above only *_if this property is inside the namespace**.
3. If **I add new property** through the `Edit Resource` with `right click` on the resource instance **ontowiki freezes** **if the new property I add first isn't one of my property**.
[Image](https://www.dropbox.com/s/o0zdhiq6ix4q8ug/freeze.png?dl=0)

If now I upload the same RDF inside another database (with another namespace), the first problem is resolved. But not the second

I have nothing interesting in the ontowiki.log, erfuts.log, queries.log and cache.log.

**Comment by white-gecko** [comment]
Maybe this is fixed on the AMSL branch already: https://github.com/amsl-project/RDFauthor

**Comment by cfrancois7** [comment]
I tested RDFauthor from the AMSL branch but that no impact on symptoms.
Maybe it's not important but if I want to edit despite the fact I can't edit when the property is inside the namespace, the `Save changes` appeared.

I tried to create a new database with a different namespace, new data inside the namespace, with "Admin" or "Common User" account => same symptoms.

**Comment by cfrancois7** [comment]
Maybe I can send you my file to reproduce the case in your side?

**Comment by white-gecko** [comment]
Since your issue actually are two issues, I've created them as #50 and #51

**Comment by white-gecko** [comment]
Please see, if these issues cover your problems.

**Comment by cfrancois7** [comment]
Yes these issues cover my problems.
Thank you.
